name: Lychee external linkcheck
on:
  schedule:
    - cron: "18 7 * * 1"
  workflow_dispatch:
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config lychee.toml ./docs
          fail: false
      - name: Summary
        run: echo "âœ… Link check complete. Review results above."
