name: Lychee external linkcheck
on:
  schedule:
    - cron: "18 7 * * 1"  
  workflow_dispatch: 
jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@f796c8b7d468feb9b8c0a46da3fac0af6874d374
        with:
          args: --config lychee.toml ./docs
          fail: false
          
      - name: Report Summary
        run: |
          echo "ðŸ“Š Link check completed!"
          echo "Check the workflow summary for details."
